# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=simplekeybinds
mod_version=1.4.3
mod_name=Simple Keybinds
description=A Fabric/(Neo)Forge mod that adds simple(r) keybinds to Minecraft.
mod_author=Dillon8775
credits=Dillon8775
license=All rights reserved unless explicitly stated.
logo=assets/simplekeybinds/icon
mc_version=mc26.2
supported_mc_versions=26.2
minecraft_version_range=[26.2, 26.3)
group=net.dillon.simplekeybinds

# Links
homepage=https://modrinth.com/mod/simple-keybinds
sources=https://github.com/Dillon8775/Simple-Keybinds
issues=https://github.com/Dillon8775/Simple-Keybinds/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=25
minecraft_version=26.2

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Balm version
balm_version=26.2.0.1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.2
modmenu_version=20.0.0-beta.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)

# Other (not required in multiloader-common.gradle)
curseforge_project_id=1011392
modrinth_project_id=EKOD7cRT
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false