# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_id=simplekeybinds
mod_version=1.3.1
mod_name=Simple Keybinds
description=Adds simpler keybinds to Minecraft.
mod_author=Dillon8775
credits=Dillon8775
license=All rights reserved.
logo=assets/simplekeybinds/icon
mc_version=mc1.21.1
supported_mc_versions=[1.21.1]
minecraft_version_range=[1.21.1, 1.21.2)
group=net.dillon.simplekeybinds

# Links
homepage=https://modrinth.com/mod/simple-keybinds
sources=https://github.com/Dillon8775/Simple-Keybinds
issues=https://github.com/Dillon8775/Simple-Keybinds/issues
discord=https://discord.gg/vfqEAn4YFy

# Common
java_version=21
minecraft_version=1.21.1

# IDs
curseforge_project_id=1011392
modrinth_project_id=EKOD7cRT

# Balm version
balm_version=21.0.56+1.21.1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=
fabric_loader_version=
modmenu_version=11.0.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=
neoforge_loader_version_range=[4,)

# Changelog and Misc
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false